### ISSUE TITLE
SSNG and SMUL condition.

### ISSUE THREAD

**Issue by sanuj** [osmanio2/multi-domain-belief-tracking#3]
https://github.com/osmanio2/multi-domain-belief-tracking/blob/1e9ec9a6e1e1638a27301065fb71eb889546c535/preprocess.py#L71

I'm not able to understand the significance of this condition. There are 388 dialogs with `SSNG` in the filename and 0 with `SMUL`. Why are they not being included for belief tracking data?

@osmanio2 Any help would be appriciated.

**Comment by budzianowski** [comment]
We were still cleaning some parts of data when experiments were conducted. This condition is needed for the MultiWOZ1 dataset only.
