### ISSUE TITLE
confused about figure1 in paper "Large-Scale Multi-Domain Belief Tracking with Knowledge Sharing"

### ISSUE THREAD

**Issue by luweishuang** [osmanio2/multi-domain-belief-tracking#4]
![WechatIMG2](https://user-images.githubusercontent.com/12368977/54975777-2c36e680-4fd3-11e9-97a3-b97f2716ae2e.jpeg)
I can't understand why multi-domain belief state tracking needs both system text and user text as input, for a dialoguage system, the user text is something which need to be generated, not exist before, and I think nlg part often behind belief tracking part. Can you give some explain about this?

**Comment by sanuj** [comment]
@budzianowski @osmanio2 I had a doubt along similar lines. The figure shows that user is replying to system, which means system utterance is from previous turn (assuming user is the first speaker, which is the case in the dataset). However, the data after preprocessing is like this:
```json
"0": {
    "user": {
        "text": "Hi I'm looking for lodging in Cambridge that includes free wifi and is upscale and expensive",
        "belief_state": {...}
    },
    "system": "I found Gonville hotel matching your requirements. Would you like to stay there?"
},
"1": {
    "user": {
        "text": "I actually am looking for a guesthouse, not a hotel.",
        "belief_state": {...}
    },
    "system": "Unfortunately, there is nothing that meets your criteria. Is there anything else I can help you with?"
}
```
As far as I can tell from the code, user and system utterance from the same turn is used to predict the turn's belief state. But system utterance of previous turn should be used, because you need the belief state to generate the current turn's system utterance. Please correct me if I'm wrong somewhere.

**Comment by taolusi** [comment]
> 
> 
> ![WechatIMG2](https://user-images.githubusercontent.com/12368977/54975777-2c36e680-4fd3-11e9-97a3-b97f2716ae2e.jpeg)
> I can't understand why multi-domain belief state tracking needs both system text and user text as input, for a dialoguage system, the user text is something which need to be generated, not exist before, and I think nlg part often behind belief tracking part. Can you give some explain about this?

In fact, the system text is what need to be generated. And nlg part is often before tracking part.

**Comment by taolusi** [comment]
> 
> 
> @budzianowski @osmanio2 I had a doubt along similar lines. The figure shows that user is replying to system, which means system utterance is from previous turn (assuming user is the first speaker, which is the case in the dataset). However, the data after preprocessing is like this:
> 
> ```json
> "0": {
>     "user": {
>         "text": "Hi I'm looking for lodging in Cambridge that includes free wifi and is upscale and expensive",
>         "belief_state": {...}
>     },
>     "system": "I found Gonville hotel matching your requirements. Would you like to stay there?"
> },
> "1": {
>     "user": {
>         "text": "I actually am looking for a guesthouse, not a hotel.",
>         "belief_state": {...}
>     },
>     "system": "Unfortunately, there is nothing that meets your criteria. Is there anything else I can help you with?"
> }
> ```
> 
> As far as I can tell from the code, user and system utterance from the same turn is used to predict the turn's belief state. But system utterance of previous turn should be used, because you need the belief state to generate the current turn's system utterance. Please correct me if I'm wrong somewhere.

Same question. Besides, do you know whether the requestable slots are considered in this work? Thanks.

**Comment by budzianowski** [comment]
Hi all,

you are right. The first system turn is 'silenced' here. So according to the set-up from the diagram the current system utterance is actually in the next turn. The data schema was created to be consistent with nlg and e2e set-up. 

@taolusi  - unfortunately we were not able run this collection with requestable slots which makes the prediction task harder.

**Comment by sz128** [comment]
> @budzianowski @osmanio2 I had a doubt along similar lines. The figure shows that user is replying to system, which means system utterance is from previous turn (assuming user is the first speaker, which is the case in the dataset). However, the data after preprocessing is like this:
> 
> ```json
> "0": {
>     "user": {
>         "text": "Hi I'm looking for lodging in Cambridge that includes free wifi and is upscale and expensive",
>         "belief_state": {...}
>     },
>     "system": "I found Gonville hotel matching your requirements. Would you like to stay there?"
> },
> "1": {
>     "user": {
>         "text": "I actually am looking for a guesthouse, not a hotel.",
>         "belief_state": {...}
>     },
>     "system": "Unfortunately, there is nothing that meets your criteria. Is there anything else I can help you with?"
> }
> ```
> 
> As far as I can tell from the code, user and system utterance from the same turn is used to predict the turn's belief state. But system utterance of previous turn should be used, because you need the belief state to generate the current turn's system utterance. Please correct me if I'm wrong somewhere.

I believe the authors do use the previous system utterance in the function `def load_woz_data(data, word_vectors, ontology, url=True)` of `main.py` : 

```
Line 239:            pre_sys = sys_v
```

**Comment by osmanio2** [comment]
> ![WechatIMG2](https://user-images.githubusercontent.com/12368977/54975777-2c36e680-4fd3-11e9-97a3-b97f2716ae2e.jpeg)
> I can't understand why multi-domain belief state tracking needs both system text and user text as input, for a dialoguage system, the user text is something which need to be generated, not exist before, and I think nlg part often behind belief tracking part. Can you give some explain about this?

As @budzianowski  and @sz128  mentioned, we do use the previous turn system utterance, because the current turn user utterance may be a response to a question asked by the system. For example, the user utterance can be 'yes please' in response to the system question 'Do you want a cheap price range?'. If we didn't include the previous turn system utterance, the belief tracker has no way of predicting the belief state (price range=cheap) for the current term.
