### ISSUE TITLE
The system response is future information in this dataset.

### ISSUE THREAD

**Issue by sz128** [osmanio2/multi-domain-belief-tracking#5]
I think the "turn" of <current user utterance, following system response> should be not right in this project. Because dialogues of this dataset always start with a user utterance, thus the following system response is not dialogue history for current state but some kind of future information. 

The right setup should be using the last system response and padding an empty system response for the first user utterance.

![image](https://user-images.githubusercontent.com/16218783/56074077-f2d9e580-5dde-11e9-89c9-bc1cb174726d.png)

**Comment by budzianowski** [comment]
That's right. Have a look at #4

**Comment by sz128** [comment]
It was misunderstood by me. Finally, I find the code in function "_load_woz_data_" where the last system response is used. Thank you.
